<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Version>5.0.0</Version>
        <Description>TheOtherRoles - MiraAPI Edition</Description>
        <Authors>Eisbison (Rewritten for MiraAPI)</Authors>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AllOfUs.MiraAPI" Version="0.4.3" />
        <PackageReference Include="AmongUs.GameLibs.Steam" Version="2026.8.18" />
        <PackageReference Include="BepInEx.IL2CPP.MSBuild" Version="2.1.0-rc.1" />
        <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.735" />
        <PackageReference Include="Reactor" Version="2.5.1-ci.384" />
    </ItemGroup>

    <Target Name="CopyCustomContent" AfterTargets="AfterBuild" Condition="Exists('$(AmongUsLatest)/BepInEx/plugins/')">
        <Copy SourceFiles="$(ProjectDir)\bin\$(Configuration)\net6.0\TheOtherRoles.dll" DestinationFolder="$(AmongUsLatest)/BepInEx/plugins/" />
    </Target>
</Project>
